deploy:
  stage: deploy
  image: google/cloud-sdk:alpine
  only:
    - master
  script:
    - echo $SERVICE_ACCOUNT > /tmp/service_account.json
    - gcloud auth activate-service-account --key-file /tmp/service_account.json
    - gcoud app deploy --project $PROJECT_ID
